In [1]:
# Numpy provides efficient storage
# It also provides better ways of handling data for processing
# It is fast
# It is easy to learn 
# Numpy uses relatively less memory to store data

In [3]:
import numpy as np


In [4]:
myarr = np.array([[3, 6, 32, 7]], np.int8)

In [5]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [6]:
myarr[0, 2]

32

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int8')

In [9]:
listarr = np.array([[1,2,3], [5, 6, 7], [0, 9, 8]])

In [10]:
listarr

array([[1, 2, 3],
       [5, 6, 7],
       [0, 9, 8]])

In [11]:
listarr.dtype

dtype('int32')

In [12]:
np.array({34, 23, 23})

array({34, 23}, dtype=object)

In [13]:
z = np.zeros((2, 5))

In [14]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace  = np.linspace(1, 50, 10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [18]:
emp = np.empty((4, 6))

In [20]:
emp

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000, -2.33597778e-310],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [22]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
n 